import type { GameRow } from "./types";

export const seedGames: GameRow[] = [
  {game_key:"1",sort_order:1,round_label:"Round 1 — Friday",scheduled_at:"2026-09-04T10:00:00-04:00",field_name:"Hillside Park Upper",team_a:"Waterloo",team_b:"Scarborough",team_a_source:null,team_b_source:null,gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"2",sort_order:2,round_label:"Round 1 — Friday",scheduled_at:"2026-09-04T10:00:00-04:00",field_name:"Hillside Park Lower",team_a:"Burlington",team_b:"Riverside",team_a_source:null,team_b_source:null,gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"3",sort_order:3,round_label:"Round 1 — Friday",scheduled_at:"2026-09-04T10:00:00-04:00",field_name:"Waterloo Park 3",team_a:"Cambridge",team_b:"YSBA",team_a_source:null,team_b_source:null,gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"4",sort_order:4,round_label:"Round 1 — Friday",scheduled_at:"2026-09-04T10:00:00-04:00",field_name:"Waterloo Park 4",team_a:"Mississauga Majors",team_b:"Whitby",team_a_source:null,team_b_source:null,gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"5",sort_order:5,round_label:"Round 1 — Friday",scheduled_at:"2026-09-04T14:00:00-04:00",field_name:"Hillside Park Upper",team_a:"Guelph",team_b:"Niagara",team_a_source:null,team_b_source:null,gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"6",sort_order:6,round_label:"Round 1 — Friday",scheduled_at:"2026-09-04T14:00:00-04:00",field_name:"Hillside Park Lower",team_a:"London",team_b:"Hamilton",team_a_source:null,team_b_source:null,gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"7",sort_order:7,round_label:"Round 2 — Friday",scheduled_at:"2026-09-04T14:00:00-04:00",field_name:"Waterloo Park 3",team_a:null,team_b:null,team_a_source:"L:1",team_b_source:"L:2",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"8",sort_order:8,round_label:"Round 2 — Friday",scheduled_at:"2026-09-04T14:00:00-04:00",field_name:"Waterloo Park 4",team_a:null,team_b:null,team_a_source:"L:3",team_b_source:"L:4",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"9",sort_order:9,round_label:"Round 2 — Friday",scheduled_at:"2026-09-04T18:00:00-04:00",field_name:"Hillside Park Upper",team_a:null,team_b:null,team_a_source:"L:5",team_b_source:"L:6",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"10",sort_order:10,round_label:"Round 2 — Friday",scheduled_at:"2026-09-04T18:00:00-04:00",field_name:"Hillside Park Lower",team_a:null,team_b:null,team_a_source:"W:1",team_b_source:"W:2",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"11",sort_order:11,round_label:"Round 2 — Friday",scheduled_at:"2026-09-04T18:00:00-04:00",field_name:"Waterloo Park 3",team_a:null,team_b:null,team_a_source:"W:3",team_b_source:"W:4",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"12",sort_order:12,round_label:"Round 2 — Friday",scheduled_at:"2026-09-04T18:00:00-04:00",field_name:"Waterloo Park 4",team_a:null,team_b:null,team_a_source:"W:5",team_b_source:"W:6",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"13",sort_order:13,round_label:"Round 3 — Saturday 10 AM",scheduled_at:"2026-09-05T10:00:00-04:00",field_name:"Waterloo Park 3",team_a:null,team_b:null,team_a_source:"W:7",team_b_source:"W:8",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"14",sort_order:14,round_label:"Round 3 — Saturday 10 AM",scheduled_at:"2026-09-05T10:00:00-04:00",field_name:"Waterloo Park 4",team_a:null,team_b:null,team_a_source:"W:9",team_b_source:"L:10",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"15",sort_order:15,round_label:"Round 3 — Saturday 10 AM",scheduled_at:"2026-09-05T10:00:00-04:00",field_name:"Hillside Park Upper",team_a:null,team_b:null,team_a_source:"L:11",team_b_source:"L:12",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"16",sort_order:16,round_label:"Round 3 — Saturday 10 AM",scheduled_at:"2026-09-05T10:00:00-04:00",field_name:"Hillside Park Lower",team_a:null,team_b:null,team_a_source:"W:11",team_b_source:"W:12",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"17",sort_order:17,round_label:"Round 4 — Saturday 2 PM",scheduled_at:"2026-09-05T14:00:00-04:00",field_name:"Waterloo Park 3",team_a:null,team_b:null,team_a_source:"W:13",team_b_source:"W:14",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"18",sort_order:18,round_label:"Round 4 — Saturday 2 PM",scheduled_at:"2026-09-05T14:00:00-04:00",field_name:"Hillside Park Upper",team_a:null,team_b:null,team_a_source:"W:15",team_b_source:"L:16",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"19",sort_order:19,round_label:"Round 4 — Saturday 2 PM",scheduled_at:"2026-09-05T14:00:00-04:00",field_name:"Hillside Park Lower",team_a:null,team_b:null,team_a_source:"W:10",team_b_source:"W:16",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"20",sort_order:20,round_label:"Round 5 — Saturday Final Four",scheduled_at:"2026-09-05T18:00:00-04:00",field_name:"Waterloo Park 3",team_a:"TBD — OBA re-pair",team_b:"TBD — OBA re-pair",team_a_source:null,team_b_source:null,gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:true,enabled:true},
  {game_key:"21",sort_order:21,round_label:"Round 5 — Saturday Final Four",scheduled_at:"2026-09-05T18:00:00-04:00",field_name:"Waterloo Park 4",team_a:"TBD — OBA re-pair",team_b:"TBD — OBA re-pair",team_a_source:null,team_b_source:null,gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:true,enabled:true},
  {game_key:"22A",sort_order:22,round_label:"Championship Path A — 2 Teams Remain",scheduled_at:"2026-09-06T10:00:00-04:00",field_name:"Waterloo Park 3",team_a:null,team_b:null,team_a_source:"W:20",team_b_source:"W:21",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"23A",sort_order:23,round_label:"Championship Path A — If Necessary",scheduled_at:"2026-09-06T14:00:00-04:00",field_name:"Waterloo Park 3",team_a:null,team_b:null,team_a_source:"W:22A",team_b_source:"L:22A",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:false,enabled:true},
  {game_key:"22B",sort_order:24,round_label:"Championship Path B — 3 Teams Remain",scheduled_at:"2026-09-06T10:00:00-04:00",field_name:"Waterloo Park 3",team_a:"TBD — OBA draw",team_b:"TBD — OBA draw",team_a_source:null,team_b_source:null,gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:true,enabled:true},
  {game_key:"23B",sort_order:25,round_label:"Championship Path B — Final",scheduled_at:"2026-09-06T14:00:00-04:00",field_name:"Waterloo Park 3",team_a:"TBD — Bye team",team_b:null,team_a_source:null,team_b_source:"W:22B",gc_game_id:null,score_a:null,score_b:null,game_status:"upcoming",is_manual_override:true,enabled:true}
];
